"""MD Simulation API.\n\nGROMACS molecular dynamics setup (gmxapi workflows, MDP files),\nshell script generation, and SLURM HPC job submission scripts.

Usage:
    python3 scripts/md_simulation_api.py <subcommand> --output <file> [options]
"""

import argparse
import json
import os
import re
import sys
import time
import urllib.parse
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any

# Locate http_client relative to this script.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

import http_client

# ---------------------------------------------------------------------------
# API Clients
# ---------------------------------------------------------------------------

CHEMBL_BASE = "https://www.ebi.ac.uk/chembl/api/data"
PDB_BASE = "https://data.rcsb.org/rest/v1/core"
ALPHAFOLD_BASE = "https://alphafold.ebi.ac.uk/api"
RCSB_FILES_BASE = "https://files.rcsb.org"
AF_FILES_BASE = "https://alphafold.ebi.ac.uk"

_CHEMBL_CLIENT = http_client.HttpClient(CHEMBL_BASE, qps=5.0)
_PDB_CLIENT = http_client.HttpClient(PDB_BASE, qps=5.0)
_ALPHAFOLD_CLIENT = http_client.HttpClient(ALPHAFOLD_BASE, qps=5.0)


def _build_url(base: str, path: str, params: dict | None = None) -> str:
    """Build a full URL from base + path + optional query parameters."""
    url = f"{base}/{path.lstrip('/')}"
    if params:
        qs = urllib.parse.urlencode(params)
        url = f"{url}?{qs}"
    return url


# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

def write_output(data: Any, output_file: str) -> None:
    """Write data to a JSON file."""
    os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, default=str)
    print(f"Success! Data written to: {output_file}")


def write_text_output(text: str, output_file: str) -> None:
    """Write plain text to a file."""
    os.makedirs(os.path.dirname(output_file) or ".", exist_ok=True)
    with open(output_file, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"Success! Script written to: {output_file}")


# ---------------------------------------------------------------------------


def cmd_generate_hpc_script(args):
    """Generate SLURM submission script for HPC jobs."""
    from datetime import datetime

    job_type = args.job_type

    # Build SLURM header
    header_lines = [
        "#!/bin/bash",
        f"#SBATCH --job-name={job_type}",
        f"#SBATCH --partition={'gpu' if args.ngpu > 0 else 'cpu'}",
        f"#SBATCH --time={args.time}",
        f"#SBATCH --mem={args.mem}",
        f"#SBATCH --cpus-per-task={args.ncpus}",
        f"#SBATCH --output={job_type}_%j.out",
        f"#SBATCH --error={job_type}_%j.err",
    ]
    if args.ngpu > 0:
        header_lines.append(
            f"#SBATCH --gres=gpu:{args.gpu}:{args.ngpu}"
        )
    if args.array:
        header_lines.append(f"#SBATCH --array={args.array}")

    header = "\n".join(header_lines)
    header += f"\n\n# Generated by Drug Discovery Wizard on {datetime.now().isoformat()}\n"

    if job_type == "reinvent":
        if not args.config:
            print("ERROR: --config required for reinvent jobs", file=sys.stderr)
            sys.exit(1)
        body = f"""
echo "Job started at: $(date)"
nvidia-smi

module purge
module load anaconda3/2024.02
conda activate {args.conda_env}

which reinvent || {{ echo "ERROR: reinvent not found"; exit 1; }}

reinvent {args.config}

echo "Job completed at: $(date)"
"""
    elif job_type == "gromacs-md":
        nsteps = args.production_ns * 500000
        body = f"""
echo "Job started at: $(date)"
nvidia-smi

module purge
module load gromacs/2024.3-gpu

WORKDIR=$SLURM_SUBMIT_DIR
cd $WORKDIR

# Energy Minimisation
gmx grompp -f em.mdp -c solv_ions.gro -p topol.top -o em.tpr
gmx mdrun -deffnm em -nb gpu -v

# NVT Equilibration (100 ps)
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
gmx mdrun -deffnm nvt -nb gpu -pme gpu -v

# NPT Equilibration (100 ps)
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr
gmx mdrun -deffnm npt -nb gpu -pme gpu -v

# Production MD ({args.production_ns} ns = {nsteps} steps @ 2 fs)
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o production.tpr
gmx mdrun -deffnm production -nb gpu -pme gpu -bonded gpu -update gpu -ntomp $SLURM_CPUS_PER_TASK -v

# Post-processing
echo "1 1" | gmx rms -s production.tpr -f production.xtc -o rmsd.xvg
echo "1" | gmx rmsf -s production.tpr -f production.xtc -o rmsf.xvg
echo "1" | gmx gyrate -s production.tpr -f production.xtc -o gyrate.xvg

echo "Job completed at: $(date)"
"""
    elif job_type == "vina-screen":
        if not args.receptor or not args.ligand_dir:
            print("ERROR: --receptor and --ligand-dir required",
                  file=sys.stderr)
            sys.exit(1)
        body = f"""
echo "Array task $SLURM_ARRAY_TASK_ID"

module purge
module load autodock-vina/1.2.5

RECEPTOR="{args.receptor}"
LIGAND_DIR="{args.ligand_dir}"
SITE_CONFIG="{args.site_config}"
OUTPUT_DIR="results"
mkdir -p $OUTPUT_DIR

LIGAND=$(ls $LIGAND_DIR/*.pdbqt | sed -n "${{SLURM_ARRAY_TASK_ID}}p")
BASENAME=$(basename $LIGAND .pdbqt)

if [ -z "$LIGAND" ]; then exit 0; fi

CENTER_X=$(python3 -c "import json; print(json.load(open('$SITE_CONFIG'))['center_x'])")
CENTER_Y=$(python3 -c "import json; print(json.load(open('$SITE_CONFIG'))['center_y'])")
CENTER_Z=$(python3 -c "import json; print(json.load(open('$SITE_CONFIG'))['center_z'])")
SIZE_X=$(python3 -c "import json; print(json.load(open('$SITE_CONFIG'))['size_x'])")
SIZE_Y=$(python3 -c "import json; print(json.load(open('$SITE_CONFIG'))['size_y'])")
SIZE_Z=$(python3 -c "import json; print(json.load(open('$SITE_CONFIG'))['size_z'])")

vina --receptor $RECEPTOR --ligand $LIGAND \\
     --center_x $CENTER_X --center_y $CENTER_Y --center_z $CENTER_Z \\
     --size_x $SIZE_X --size_y $SIZE_Y --size_z $SIZE_Z \\
     --exhaustiveness 32 --num_modes 9 \\
     --out $OUTPUT_DIR/${{BASENAME}}_out.pdbqt \\
     --log $OUTPUT_DIR/${{BASENAME}}_log.txt

echo "Done: $BASENAME"
"""
    else:
        print(f"ERROR: Unknown job type: {job_type}", file=sys.stderr)
        sys.exit(1)

    script = header + "\n" + body
    write_text_output(script, args.output)

# ---------------------------------------------------------------------------


def cmd_generate_md_setup(args):
    """Generate GROMACS MD system setup script."""
    from datetime import datetime

    nsteps = args.production_ns * 500000

    script = f"""#!/bin/bash
# GROMACS MD System Setup Script
# Generated by Drug Discovery Wizard on {datetime.now().isoformat()}
set -euo pipefail

PDB_FILE="{args.pdb}"
FF="{args.ff}"
WATER="{args.water}"
BOX_DIST={args.box_dist}

echo "=== GROMACS MD Setup ==="
echo "Input: $PDB_FILE | FF: $FF | Water: $WATER"

# Generate topology
gmx pdb2gmx -f $PDB_FILE -o protein.gro -p topol.top -ignh -ff $FF -water $WATER

# Simulation box
gmx editconf -f protein.gro -o box.gro -c -d $BOX_DIST -bt dodecahedron

# Solvate
gmx solvate -cp box.gro -cs spc216.gro -o solv.gro -p topol.top

# Add ions
gmx grompp -f ions.mdp -c solv.gro -p topol.top -o ions.tpr -maxwarn 1
echo "SOL" | gmx genion -s ions.tpr -o solv_ions.gro -p topol.top -pname NA -nname CL -neutral

echo "=== Setup Complete ==="
echo "Files: protein.gro, box.gro, solv.gro, solv_ions.gro, topol.top"

# Generate MDP files
cat > em.mdp << 'EOF'
integrator  = steep
emtol       = 1000.0
emstep      = 0.01
nsteps      = 50000
nstlist     = 10
cutoff-scheme = Verlet
ns_type     = grid
coulombtype = PME
rcoulomb    = 1.0
rvdw        = 1.0
pbc         = xyz
EOF

cat > nvt.mdp << 'EOF'
define      = -DPOSRES
integrator  = md
nsteps      = 50000
dt          = 0.002
nstxout-compressed = 5000
nstenergy   = 5000
nstlog      = 5000
continuation = no
constraint_algorithm = lincs
constraints = h-bonds
cutoff-scheme = Verlet
nstlist     = 10
rcoulomb    = 1.0
rvdw        = 1.0
coulombtype = PME
tcoupl      = V-rescale
tc-grps     = Protein Non-Protein
tau_t       = 0.1   0.1
ref_t       = 300   300
pcoupl      = no
pbc         = xyz
gen_vel     = yes
gen_temp    = 300
gen_seed    = -1
EOF

cat > npt.mdp << 'EOF'
define      = -DPOSRES
integrator  = md
nsteps      = 50000
dt          = 0.002
nstxout-compressed = 5000
nstenergy   = 5000
nstlog      = 5000
continuation = yes
constraint_algorithm = lincs
constraints = h-bonds
cutoff-scheme = Verlet
nstlist     = 10
rcoulomb    = 1.0
rvdw        = 1.0
coulombtype = PME
tcoupl      = V-rescale
tc-grps     = Protein Non-Protein
tau_t       = 0.1   0.1
ref_t       = 300   300
pcoupl      = Parrinello-Rahman
pcoupltype  = isotropic
tau_p       = 2.0
ref_p       = 1.0
compressibility = 4.5e-5
pbc         = xyz
gen_vel     = no
EOF

cat > md.mdp << EOFMD
integrator  = md
nsteps      = {nsteps}
dt          = 0.002
nstxout-compressed = 5000
nstenergy   = 5000
nstlog      = 5000
continuation = yes
constraint_algorithm = lincs
constraints = h-bonds
cutoff-scheme = Verlet
nstlist     = 10
rcoulomb    = 1.0
rvdw        = 1.0
coulombtype = PME
tcoupl      = V-rescale
tc-grps     = Protein Non-Protein
tau_t       = 0.1   0.1
ref_t       = 300   300
pcoupl      = Parrinello-Rahman
pcoupltype  = isotropic
tau_p       = 2.0
ref_p       = 1.0
compressibility = 4.5e-5
pbc         = xyz
gen_vel     = no
EOFMD

cat > ions.mdp << 'EOF'
integrator  = steep
emtol       = 1000.0
emstep      = 0.01
nsteps      = 50000
nstlist     = 1
cutoff-scheme = Verlet
ns_type     = grid
coulombtype = cutoff
rcoulomb    = 1.0
rvdw        = 1.0
pbc         = xyz
EOF

echo "MDP files: em.mdp, nvt.mdp, npt.mdp, md.mdp, ions.mdp"
echo "Ready for SLURM submission."
"""

    write_text_output(script, args.output)


def cmd_gmxapi_setup(args):
    """gmxapi workflow generation — delegates to gmxapi_setup.py."""
    from gmxapi_setup import generate_gmxapi_workflow, generate_mdp
    script = generate_gmxapi_workflow(
        pdb=args.pdb,
        ff=args.ff,
        water=args.water,
        production_ns=args.production_ns,
        box_dist=args.box_dist,
        temperature=args.temperature,
    )
    out_dir = Path(args.output).parent
    out_dir.mkdir(parents=True, exist_ok=True)
    for mdp_type in ["ions", "em", "nvt", "npt", "production"]:
        mdp_content = generate_mdp(mdp_type, args.production_ns)
        mdp_name = "md.mdp" if mdp_type == "production" else f"{mdp_type}.mdp"
        (out_dir / mdp_name).write_text(mdp_content)
    Path(args.output).write_text(script)
    print(f"[OK] gmxapi workflow + MDP files saved to {out_dir}")


def cmd_gmxapi_validate(args):
    """MDP validation — delegates to gmxapi_setup.py."""
    from gmxapi_setup import validate_mdp
    results = []
    for mdp_file in args.mdp:
        results.append(validate_mdp(mdp_file))
    report = {
        "total_files": len(results),
        "all_valid": all(r["valid"] for r in results),
        "files": results,
    }
    write_output(report, args.output)
    for r in results:
        status = "VALID" if r["valid"] else "INVALID"
        print(f"  {r['file']}: {status}")


# ---------------------------------------------------------------------------
# CLI definition
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="MD Simulation — GROMACS setup, MDP generation, HPC scripts"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # --- gmxapi-setup ---
    p_gmxapi = sub.add_parser("gmxapi-setup",
        help="Generate gmxapi Python workflow + MDP files")
    p_gmxapi.add_argument("--pdb", required=True, help="Input PDB file")
    p_gmxapi.add_argument("--ff", default="charmm36", help="Force field")
    p_gmxapi.add_argument("--water", default="tip3p", help="Water model")
    p_gmxapi.add_argument("--production-ns", type=float, default=100.0,
                           help="Production MD length in ns")
    p_gmxapi.add_argument("--box-dist", type=float, default=1.2,
                           help="Box distance from solute (nm)")
    p_gmxapi.add_argument("--temperature", type=float, default=300.0,
                           help="Temperature in K")
    p_gmxapi.add_argument("--output", required=True,
                           help="Output Python script path")
    p_gmxapi.set_defaults(func=cmd_gmxapi_setup)

    # --- gmxapi-validate ---
    p_gval = sub.add_parser("gmxapi-validate",
        help="Validate GROMACS MDP files")
    p_gval.add_argument("--mdp", nargs="+", required=True,
                         help="MDP files to validate")
    p_gval.add_argument("--output", required=True)
    p_gval.set_defaults(func=cmd_gmxapi_validate)

    # --- generate-md-setup ---
    p_md = sub.add_parser("generate-md-setup",
        help="Generate GROMACS MD setup shell script")
    p_md.add_argument("--pdb", required=True)
    p_md.add_argument("--ff", default="charmm36", help="Force field")
    p_md.add_argument("--water", default="tip3p", help="Water model")
    p_md.add_argument("--box-dist", type=float, default=1.2,
                       help="Box distance (nm)")
    p_md.add_argument("--production-ns", type=int, default=100)
    p_md.add_argument("--output", required=True)
    p_md.set_defaults(func=cmd_generate_md_setup)

    # --- generate-hpc-script ---
    p_hpc = sub.add_parser("generate-hpc-script",
        help="Generate SLURM HPC submission script")
    p_hpc.add_argument("--job-type", required=True,
                        choices=["reinvent", "gromacs-md", "vina-screen"])
    p_hpc.add_argument("--config", default=None)
    p_hpc.add_argument("--receptor", default=None)
    p_hpc.add_argument("--ligand-dir", default="ligands")
    p_hpc.add_argument("--conda-env", default="reinvent4")
    p_hpc.add_argument("--site-config", default="binding_site.json")
    p_hpc.add_argument("--production-ns", type=int, default=100)
    p_hpc.add_argument("--gpu", default="a100")
    p_hpc.add_argument("--ngpu", type=int, default=1)
    p_hpc.add_argument("--ncpus", type=int, default=8)
    p_hpc.add_argument("--mem", default="64G")
    p_hpc.add_argument("--time", default="24:00:00")
    p_hpc.add_argument("--array", default=None)
    p_hpc.add_argument("--output", required=True)
    p_hpc.set_defaults(func=cmd_generate_hpc_script)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
